import os
from dotenv import load_dotenv

load_dotenv()

ENDPOINT = os.getenv("ENDPOINT")
MODEL = os.getenv("MODEL")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
QDRANT_COLLECTION = os.getenv("QDRANT_COLLECTION")
QDRANT_ENDPOINT = os.getenv("QDRANT_ENDPOINT")
API_PORT = int(os.getenv("API_PORT"))
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL")

CODE_REVIEW_PROJECT_PATH = os.getenv("CODE_REVIEW_PROJECT_PATH")
CODE_REVIEW_CURRENT_BRANCH = os.getenv("CODE_REVIEW_CURRENT_BRANCH")
CODE_REVIEW_PRODUCTION_BRANCH = os.getenv("CODE_REVIEW_PRODUCTION_BRANCH")

SLACK_API_ENDPOINT = os.getenv("SLACK_API_ENDPOINT")
SLACK_API_TOKEN = os.getenv("SLACK_API_TOKEN")
SLACK_COOKIE = os.getenv("SLACK_COOKIE")